"""sec

Revision ID: 27b7e67ac250
Revises: 1c0e1685054a
Create Date: 2024-02-25 16:56:47.631092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b7e67ac250'
down_revision = '1c0e1685054a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_components', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('tob',
               existing_type=sa.TIME(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_components', schema=None) as batch_op:
        batch_op.alter_column('tob',
               existing_type=sa.String(length=50),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
