"""just added AllFormComp

Revision ID: 9e60fe7ca0b8
Revises: b03f4a996bc2
Create Date: 2024-02-25 00:42:25.772642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e60fe7ca0b8'
down_revision = 'b03f4a996bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('tob', sa.Time(), nullable=True),
    sa.Column('drop', sa.String(length=50), nullable=True),
    sa.Column('radio', sa.Enum('SENT', 'CANCELED', 'RECEIVED', 'ACCEPTED', 'REJECTED', name='radioenum'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_components')
    # ### end Alembic commands ###
