"""updated default values of existing models

Revision ID: a1592548e3fb
Revises: 
Create Date: 2023-12-24 17:43:34.518988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1592548e3fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('lname', sa.String(length=32), nullable=True),
    sa.Column('fname', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('friends_ids', sa.String(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chathistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=100), nullable=True),
    sa.Column('frm_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frm_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'CANCELED', 'RECEIVED', 'ACCEPTED', 'REJECTED', name='myenum'), nullable=True),
    sa.Column('frm_user', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frm_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rtcuserinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator', sa.Boolean(), nullable=True),
    sa.Column('sdp', sa.String(length=5000), nullable=True),
    sa.Column('answer', sa.String(length=5000), nullable=True),
    sa.Column('frm_user', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frm_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_brief_rec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lmsgtime', sa.DateTime(), nullable=True),
    sa.Column('lmsg_is_delivered', sa.Boolean(), nullable=True),
    sa.Column('lmsg_is_read', sa.Boolean(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_of_brothers', sa.Integer(), nullable=True),
    sa.Column('married_brother', sa.Integer(), nullable=True),
    sa.Column('no_of_sisters', sa.Integer(), nullable=True),
    sa.Column('married_sister', sa.Integer(), nullable=True),
    sa.Column('family_location', sa.String(length=50), nullable=True),
    sa.Column('native_place', sa.String(length=50), nullable=True),
    sa.Column('affluence', sa.String(length=50), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('father',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=50), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('father')
    op.drop_table('family_info')
    op.drop_table('chat_brief_rec')
    op.drop_table('rtcuserinfo')
    op.drop_table('requests')
    op.drop_table('profile')
    op.drop_table('chathistory')
    op.drop_table('user')
    # ### end Alembic commands ###
