"""updated default values of existing models

Revision ID: e2f12752b586
Revises: a1592548e3fb
Create Date: 2023-12-24 17:58:21.173913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f12752b586'
down_revision = 'a1592548e3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chathistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('SENDING', 'SENT', 'FAILED', 'DELIVERED', 'READ', name='chatenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chathistory', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
