"""initial migrations

Revision ID: f0333dc311db
Revises: 
Create Date: 2023-12-02 17:08:38.860629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0333dc311db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_of_brothers', sa.Integer(), nullable=True),
    sa.Column('married_brother', sa.Integer(), nullable=True),
    sa.Column('no_of_sisters', sa.Integer(), nullable=True),
    sa.Column('married_sister', sa.Integer(), nullable=True),
    sa.Column('family_location', sa.String(length=50), nullable=True),
    sa.Column('native_place', sa.String(length=50), nullable=True),
    sa.Column('affluence', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('lname', sa.String(length=32), nullable=True),
    sa.Column('fname', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('friends_ids', sa.String(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chathistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=True),
    sa.Column('frm_user', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frm_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('family_information_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_information_id'], ['family_information.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('frm_user', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frm_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rtcuserinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator', sa.Boolean(), nullable=True),
    sa.Column('sdp', sa.String(length=5000), nullable=True),
    sa.Column('answer', sa.String(length=5000), nullable=True),
    sa.Column('frm_user', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frm_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rtcuserinfo')
    op.drop_table('requests')
    op.drop_table('profile')
    op.drop_table('chathistory')
    op.drop_table('user')
    op.drop_table('family_information')
    # ### end Alembic commands ###
