openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about users and profile"
  version: "1.0.0"
servers:
  - url: "/api"

components:

  schemas:
    SignUpData:
      type: "object"
      required:
        - fname
     
      properties:
        fname:
          type: "string"
        
    
    
      type: "object"
      required:
        - fname
      properties:
        fname:
          type: "string"
        

  


paths:
  
  /users:
    get:
      operationId: "users.read_all"
      tags:
        - "People"
      summary: "Read the list of users"
      responses:
        "200":
          description: "Successfully read users list"
      
  
  /signup:
    post:
      operationId: "users.signup"
      tags:
        - People
      summary: "Create a user"
      requestBody:
        description: "User to create"
        required: true
        content:
          application/json:
            schema:
              x-body-name: "signup_data"
              $ref: "#/components/schemas/SignUpData"
      responses:
        "201":
          description: "Successfully created user"
